title: Pudgy Boston
email: pudgyboston@gmail.com
description: >-
  The food travels of PFAH + EWOO
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blackmathdavey.github.io/pudgyboston" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pudgyboston
# facebook_username: pudgyboston
# instagram_username: pudgyboston
# github_username:  blackmathdavey

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
